B cycle-values deband-iterations "2" "3" "4" ; cycle-values deband-threshold "35" "45 "60" ; cycle-values deband-range "20" "25" "30" ; cycle-values deband-grain "5" "15" "30" ; show-text "Deband: ${deband-iterations}:${deband-threshold}:${deband-range}:${deband-grain}"
h cycle audio
H cycle audio down
i cycle interpolation
CTRL+h cycle-values hwdec "auto-copy" "no"
t script-message-to console type "set time-pos "
CTRL+1 cycle-values tone-mapping "spline" "bt.2446a" "st2094-40" ; show-text "Tone-mapping: ${tone-mapping}" 
