# =========================
# GENERAL / PLAYBACK
# =========================
force-seekable=yes
keep-open=always
resume-playback=no
autocreate-playlist=same
log-file=~~/../mpv-log.txt

# =========================
# CACHE / DEMUXER
# =========================
cache=yes                               # use large RAM cache even for local files
cache-secs=300                          # very large cache (requires cache=yes)
demuxer-max-back-bytes=300M             # improves backward seeking
demuxer-max-bytes=300M                  # improves forward buffering

# =========================
# VIDEO OUTPUT
# =========================
vo=gpu-next

# =========================
# AUDIO
# =========================
volume=50
volume-max=200
alang=en,eng                            # preferred audio languages

# =========================
# SUBTITLES
# =========================
slang=en,eng                            # preferred subtitle languages
sub-font='Aptos'
sub-font-size=60
sub-border-size=1
sub-color='#FFFFFF'
blend-subtitles=video                   # improve subtitle performance with interpolation=yes
sub-scale-with-window=no
sub-use-margins=no
sub-fix-timing=no

# =========================
# OSD / OSC
# =========================
osc=yes
osd-bar=no
osd-align-x=right
osd-font-size=24
osd-font='Aptos Display Bold'
osd-border-size=1
osd-color='#CCFFFFFF'

# =========================
# VIDEO QUALITY / RENDERING
# =========================
#profile=fast
profile=high-quality                    # switch to "fast" on igpu or battery
dscale=catmull_rom
#gpu-api=vulkan

# Hardware decoding
hwdec=auto-copy

# Debanding
deband=no
deband-iterations=2
deband-threshold=35
deband-range=20
deband-grain=5

# HDR / color
target-colorspace-hint=yes
tone-mapping=spline
hdr-compute-peak=no

# =========================
# SYNC / SMOOTHING
# =========================
#video-sync=display-resample
interpolation=no                        # enable only with a display- sync mode

# Temporal scaling (frame interpolation tuning)
tscale=sphinx
tscale-blur=0.6991556596428412
tscale-radius=1.0
tscale-clamp=0.0

# =========================
# SCREENSHOTS
# =========================

screenshot-template="%x/Screenshots/Screenshot-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"
screenshot-format=png
screenshot-png-compression=0
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes
